name: Makefile CI

on:
  push:
    branches: [ "main" ]
    paths:
      - app/**
      - docker/**
      - Makefile
      - docker-compose.yml
      - .github/workflows/makefile.yml
      - pypproject.toml
      - poetry.lock
      - requirements.txt
  pull_request:
    branches: [ "main" ]
    paths:
      - app/**
      - docker/**
      - Makefile
      - docker-compose.yml
      - .github/workflows/makefile.yml
      - pypproject.toml
      - poetry.lock
      - requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        IMAGE="patientyesterday10/mastobot_covid19"
        echo ::set-output name=tagged_image::${IMAGE}:${TAG}
        echo ::set-output name=tag::${TAG}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        # Key is named differently to avoid collision
        key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-multi-buildx

    - name: Build Production Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Dockerfile
        push: false
        tags: ${{ steps.prep.outputs.tagged_image }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
