name: Makefile CI

on:
  push:
    branches: [ "main" ]
    paths:
      - app/**
      - docker/**
      - Makefile
      - docker-compose.yml
      - .github/workflows/makefile.yml
      - pypproject.toml
      - poetry.lock
      - requirements.txt
  pull_request:
    branches: [ "main" ]
    paths:
      - app/**
      - docker/**
      - Makefile
      - docker-compose.yml
      - .github/workflows/makefile.yml
      - pypproject.toml
      - poetry.lock
      - requirements.txt

env:
  CACHE_IMAGE: patientyesterday10/mastobot_covid19
  CACHE_TAG: ${{ github.sha }}
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build from dockerfile
      run: |
        docker build \
          --cache-from $CACHE_IMAGE:$CACHE_TAG \
          --tag $CACHE_IMAGE:$CACHE_TAG \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file docker/Dockerfile \
        .
