name: Makefile CI

on:
  push:
    branches: [ "main" ]
    paths:
      - app/**
      - docker/**
      - Makefile
      - docker-compose.yml
      - .github/workflows/makefile.yml
      - pypproject.toml
      - poetry.lock
      - requirements.txt

env:
  CACHE_IMAGE: ghcr.io/patientyesterday10/mastobot_covid19
  CACHE_TAG: latest
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build from dockerfile
      run: |
        docker build \
          --cache-from $CACHE_IMAGE:latest \
          --tag $CACHE_IMAGE:latest \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
            --file docker/Dockerfile \
        .

    - name: Push to GitHub Container Registry
      run: |
        docker push $CACHE_IMAGE:latest
        
