name: Scheduled Post to Mastodon
on:
  schedule:
    - cron: "0 13 * * *"
    #- cron: "15 3 * * 6"
  workflow_dispatch:

env:
  MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
  MASTODON_API_BASE_URL: https://botsin.space/
  CACHE_IMAGE: ghcr.io/patientyesterday10/mastobot_covid19
  CACHE_TAG: latest
  DOCKER_BUILDKIT: 1

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build from dockerfile
      run: |
        docker build \
         --cache-from $CACHE_IMAGE:latest \
         --tag $CACHE_IMAGE:latest \
         --build-arg BUILDKIT_INLINE_CACHE=1 \
           --file docker/Dockerfile \
        .

    - name: Push to GitHub Container Registry
      run: |
        docker push $CACHE_IMAGE:latest

    - name: Run docker-compose
      run: |
        CURRENT_UID=$(id -u):$(id -g) docker-compose up

