name: Scheduled Job
env: 
  MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
  MASTODON_API_BASE_URL: https://botsin.space/
  CACHE_IMAGE: patientyesterday10/mastobot_covid19
  CACHE_TAG: latest
  DOCKER_BUILDKIT: 1

on:
    schedule:
    - cron: "0 13 * * 1-5"
    - cron: "0 2 * * 6"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build from dockerfile
        run: |
          docker build \
            --cache-from $CACHE_IMAGE:$CACHE_TAG \
            --tag $CACHE_IMAGE:$CACHE_TAG \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
              --file docker/Dockerfile \
          .
